version: '3.8'

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=seu_username
      - POSTGRES_PASSWORD=sua_senha
      - POSTGRES_DB=gestao_vagas